version: 2

updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 10
    groups:
      sokol:
        patterns:
          - "lib/sokol"
          - "lib/sokol-tools-bin"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
