name: Release prebuild binaries
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - name: Download the latest release
        uses: robinraju/release-downloader@v1.12
        id: pull_latest_release
        continue-on-error: true
        with:
          filename: "yoMMD-win-*.zip"
          zipBall: true
          latest: true
          extract: true
          out-file-path: "latest-release"
      - name: Check version between latest release and latest source code
        if: ${{ steps.pull_latest_release.outcome == 'success' }}
        run: |
          version_release=$(./latest-release/yoMMD.exe --version | sed 's/^version: *//i')
          version_source=$(./scripts/gen-version-string)
          if [[ "$version_release" == "$version_source" ]]; then
            # No need to create a new release because there's no updates in this repository.
            exit 1
          fi

  build-release-hash:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      commit_hash: ${{ steps.build-hash.outputs.commit_hash }}
      version_string: ${{ steps.build-hash.outputs.version_string }}
    steps:
      - uses: actions/checkout@v6
      - id: build-hash
        run: |
          {
            echo "commit_hash=$(git log -1 --format="%h")"
            echo "version_string=$(./scripts/gen-version-string)"
          } >> "$GITHUB_OUTPUT"

  build-on-windows:
    needs:
      - check-create-release
      - build-release-hash
    runs-on: windows-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          release: false
          install: >-
            make
            zip
            git
            mingw-w64-ucrt-x86_64-binutils
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-diffutils
      - name: Build submodule libraries
        uses: ./.github/actions/build-submodules
        with:
          shell: msys2 {0}
      - name: Build binary
        run: make release -j
      - name: Package
        id: package
        run: |
          version_string="${{ needs.build-release-hash.outputs.version_string }}"
          package_name="./yoMMD-win-$(uname -m)-${version_string}.zip"
          mv release/yoMMD.exe yoMMD.exe
          zip $package_name yoMMD.exe
          echo "package_name=$package_name" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v7
        with:
          name: artifact-windows
          if-no-files-found: error
          path: ${{ steps.package.outputs.package_name }}

  build-on-macos:
    needs:
      - check-create-release
      - build-release-hash
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Setup build tools
        run: brew install --formula cmake
      - name: Show environment
        run: |
          uname -a
          clang++ --version
      - name: Build submodules
        uses: ./.github/actions/build-submodules/
        with:
          shell: bash
      - run: make -j app
      - id: package
        run: |
          version_string="${{ needs.build-release-hash.outputs.version_string }}"
          package_name="./package/yoMMD-macos-$(uname -m)-${version_string}.zip"
          mv ./package/yoMMD.app ./yoMMD.app
          zip -r "$package_name" ./yoMMD.app
          echo "package_name=$package_name" >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v7
        with:
          name: artifact-macos
          if-no-files-found: error
          path: ${{ steps.package.outputs.package_name }}

  create-release:
    needs:
      - build-release-hash
      - build-on-windows
      - build-on-macos
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Unpack artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: artifact-*
          merge-multiple: true
      - name: Debug info
        run: |
          ls -l
          if type tree >/dev/null; then
            tree .
          fi
      - id: package
        run: |
          cat <<-EOF >> "$GITHUB_OUTPUT"
            tag_name="${{ needs.build-release-hash.outputs.version_string }}"
          EOF
      - name: Create CHANGELOG
        id: changelog
        run: |
          commit_hash="${{ needs.build-release-hash.outputs.commit_hash }}"
          changelog_file="./CHANGELOG.md"
          cat <<EOF >> "$changelog_file"
          # General information

          Version: ${{ needs.build-release-hash.outputs.version_string }}
          Documents:
           - [Configuration](https://github.com/mityu/yoMMD/blob/${commit_hash}/doc/configuration.rst)
           - [Operation Guide](https://github.com/mityu/yoMMD/blob/${commit_hash}/doc/operation-guide.rst)

          # Notes for macOS binary

          Since the pre-build binary is not signed with an Apple Developer ID, macOS will show an error when you're opening the downloaded yoMMD.app.
          In order to open it, you need to remove the quarantine attribute.

          \`\`\`sh
          xattr -dr com.apple.quarantine /path/to/yoMMD.app
          \`\`\`
          EOF
          echo "changelog_file=$changelog_file" >> "$GITHUB_OUTPUT"
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: yoMMD-*-${{ needs.build-release-hash.outputs.version_string }}.zip
          tag_name: ${{ steps.package.outputs.tag_name }}
          body_path: ${{ steps.changelog.outputs.changelog_file }}
          draft: false
          prerelease: false
